// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayProto.proto

package protobuf.http;

public final class PayProto {
  private PayProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetPayHTMLCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.GetPayHTMLC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    int getHOpCode();

    /**
     * <pre>
     *订单id
     * </pre>
     *
     * <code>optional string orderRecordId = 2;</code>
     */
    java.lang.String getOrderRecordId();
    /**
     * <pre>
     *订单id
     * </pre>
     *
     * <code>optional string orderRecordId = 2;</code>
     */
    com.google.protobuf.ByteString
        getOrderRecordIdBytes();
  }
  /**
   * Protobuf type {@code protobuf.http.GetPayHTMLC}
   */
  public  static final class GetPayHTMLC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.GetPayHTMLC)
      GetPayHTMLCOrBuilder {
    // Use GetPayHTMLC.newBuilder() to construct.
    private GetPayHTMLC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetPayHTMLC() {
      hOpCode_ = 0;
      orderRecordId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetPayHTMLC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              hOpCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              orderRecordId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.PayProto.GetPayHTMLC.class, protobuf.http.PayProto.GetPayHTMLC.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private int hOpCode_;
    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    public int getHOpCode() {
      return hOpCode_;
    }

    public static final int ORDERRECORDID_FIELD_NUMBER = 2;
    private volatile java.lang.Object orderRecordId_;
    /**
     * <pre>
     *订单id
     * </pre>
     *
     * <code>optional string orderRecordId = 2;</code>
     */
    public java.lang.String getOrderRecordId() {
      java.lang.Object ref = orderRecordId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderRecordId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *订单id
     * </pre>
     *
     * <code>optional string orderRecordId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrderRecordIdBytes() {
      java.lang.Object ref = orderRecordId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderRecordId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hOpCode_ != 0) {
        output.writeInt32(1, hOpCode_);
      }
      if (!getOrderRecordIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderRecordId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hOpCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hOpCode_);
      }
      if (!getOrderRecordIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderRecordId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.PayProto.GetPayHTMLC)) {
        return super.equals(obj);
      }
      protobuf.http.PayProto.GetPayHTMLC other = (protobuf.http.PayProto.GetPayHTMLC) obj;

      boolean result = true;
      result = result && (getHOpCode()
          == other.getHOpCode());
      result = result && getOrderRecordId()
          .equals(other.getOrderRecordId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode();
      hash = (37 * hash) + ORDERRECORDID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderRecordId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.PayProto.GetPayHTMLC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.PayProto.GetPayHTMLC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.GetPayHTMLC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.GetPayHTMLC)
        protobuf.http.PayProto.GetPayHTMLCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.PayProto.GetPayHTMLC.class, protobuf.http.PayProto.GetPayHTMLC.Builder.class);
      }

      // Construct using protobuf.http.PayProto.GetPayHTMLC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = 0;

        orderRecordId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLC_descriptor;
      }

      public protobuf.http.PayProto.GetPayHTMLC getDefaultInstanceForType() {
        return protobuf.http.PayProto.GetPayHTMLC.getDefaultInstance();
      }

      public protobuf.http.PayProto.GetPayHTMLC build() {
        protobuf.http.PayProto.GetPayHTMLC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.PayProto.GetPayHTMLC buildPartial() {
        protobuf.http.PayProto.GetPayHTMLC result = new protobuf.http.PayProto.GetPayHTMLC(this);
        result.hOpCode_ = hOpCode_;
        result.orderRecordId_ = orderRecordId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.PayProto.GetPayHTMLC) {
          return mergeFrom((protobuf.http.PayProto.GetPayHTMLC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.PayProto.GetPayHTMLC other) {
        if (other == protobuf.http.PayProto.GetPayHTMLC.getDefaultInstance()) return this;
        if (other.getHOpCode() != 0) {
          setHOpCode(other.getHOpCode());
        }
        if (!other.getOrderRecordId().isEmpty()) {
          orderRecordId_ = other.orderRecordId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.PayProto.GetPayHTMLC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.PayProto.GetPayHTMLC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int hOpCode_ ;
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public int getHOpCode() {
        return hOpCode_;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder setHOpCode(int value) {
        
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object orderRecordId_ = "";
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>optional string orderRecordId = 2;</code>
       */
      public java.lang.String getOrderRecordId() {
        java.lang.Object ref = orderRecordId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderRecordId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>optional string orderRecordId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOrderRecordIdBytes() {
        java.lang.Object ref = orderRecordId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderRecordId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>optional string orderRecordId = 2;</code>
       */
      public Builder setOrderRecordId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderRecordId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>optional string orderRecordId = 2;</code>
       */
      public Builder clearOrderRecordId() {
        
        orderRecordId_ = getDefaultInstance().getOrderRecordId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>optional string orderRecordId = 2;</code>
       */
      public Builder setOrderRecordIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderRecordId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.GetPayHTMLC)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.GetPayHTMLC)
    private static final protobuf.http.PayProto.GetPayHTMLC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.PayProto.GetPayHTMLC();
    }

    public static protobuf.http.PayProto.GetPayHTMLC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetPayHTMLC>
        PARSER = new com.google.protobuf.AbstractParser<GetPayHTMLC>() {
      public GetPayHTMLC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetPayHTMLC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetPayHTMLC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPayHTMLC> getParserForType() {
      return PARSER;
    }

    public protobuf.http.PayProto.GetPayHTMLC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetPayHTMLSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.http.GetPayHTMLS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    int getHOpCode();

    /**
     * <pre>
     *支付界面
     * </pre>
     *
     * <code>optional string payHtml = 2;</code>
     */
    java.lang.String getPayHtml();
    /**
     * <pre>
     *支付界面
     * </pre>
     *
     * <code>optional string payHtml = 2;</code>
     */
    com.google.protobuf.ByteString
        getPayHtmlBytes();
  }
  /**
   * Protobuf type {@code protobuf.http.GetPayHTMLS}
   */
  public  static final class GetPayHTMLS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.http.GetPayHTMLS)
      GetPayHTMLSOrBuilder {
    // Use GetPayHTMLS.newBuilder() to construct.
    private GetPayHTMLS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetPayHTMLS() {
      hOpCode_ = 0;
      payHtml_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetPayHTMLS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              hOpCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              payHtml_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.http.PayProto.GetPayHTMLS.class, protobuf.http.PayProto.GetPayHTMLS.Builder.class);
    }

    public static final int HOPCODE_FIELD_NUMBER = 1;
    private int hOpCode_;
    /**
     * <code>optional int32 hOpCode = 1;</code>
     */
    public int getHOpCode() {
      return hOpCode_;
    }

    public static final int PAYHTML_FIELD_NUMBER = 2;
    private volatile java.lang.Object payHtml_;
    /**
     * <pre>
     *支付界面
     * </pre>
     *
     * <code>optional string payHtml = 2;</code>
     */
    public java.lang.String getPayHtml() {
      java.lang.Object ref = payHtml_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payHtml_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *支付界面
     * </pre>
     *
     * <code>optional string payHtml = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPayHtmlBytes() {
      java.lang.Object ref = payHtml_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payHtml_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hOpCode_ != 0) {
        output.writeInt32(1, hOpCode_);
      }
      if (!getPayHtmlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, payHtml_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hOpCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hOpCode_);
      }
      if (!getPayHtmlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, payHtml_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.http.PayProto.GetPayHTMLS)) {
        return super.equals(obj);
      }
      protobuf.http.PayProto.GetPayHTMLS other = (protobuf.http.PayProto.GetPayHTMLS) obj;

      boolean result = true;
      result = result && (getHOpCode()
          == other.getHOpCode());
      result = result && getPayHtml()
          .equals(other.getPayHtml());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHOpCode();
      hash = (37 * hash) + PAYHTML_FIELD_NUMBER;
      hash = (53 * hash) + getPayHtml().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.http.PayProto.GetPayHTMLS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.http.PayProto.GetPayHTMLS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.http.GetPayHTMLS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.http.GetPayHTMLS)
        protobuf.http.PayProto.GetPayHTMLSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.http.PayProto.GetPayHTMLS.class, protobuf.http.PayProto.GetPayHTMLS.Builder.class);
      }

      // Construct using protobuf.http.PayProto.GetPayHTMLS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hOpCode_ = 0;

        payHtml_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.http.PayProto.internal_static_protobuf_http_GetPayHTMLS_descriptor;
      }

      public protobuf.http.PayProto.GetPayHTMLS getDefaultInstanceForType() {
        return protobuf.http.PayProto.GetPayHTMLS.getDefaultInstance();
      }

      public protobuf.http.PayProto.GetPayHTMLS build() {
        protobuf.http.PayProto.GetPayHTMLS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.http.PayProto.GetPayHTMLS buildPartial() {
        protobuf.http.PayProto.GetPayHTMLS result = new protobuf.http.PayProto.GetPayHTMLS(this);
        result.hOpCode_ = hOpCode_;
        result.payHtml_ = payHtml_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.http.PayProto.GetPayHTMLS) {
          return mergeFrom((protobuf.http.PayProto.GetPayHTMLS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.http.PayProto.GetPayHTMLS other) {
        if (other == protobuf.http.PayProto.GetPayHTMLS.getDefaultInstance()) return this;
        if (other.getHOpCode() != 0) {
          setHOpCode(other.getHOpCode());
        }
        if (!other.getPayHtml().isEmpty()) {
          payHtml_ = other.payHtml_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.http.PayProto.GetPayHTMLS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.http.PayProto.GetPayHTMLS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int hOpCode_ ;
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public int getHOpCode() {
        return hOpCode_;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder setHOpCode(int value) {
        
        hOpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hOpCode = 1;</code>
       */
      public Builder clearHOpCode() {
        
        hOpCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object payHtml_ = "";
      /**
       * <pre>
       *支付界面
       * </pre>
       *
       * <code>optional string payHtml = 2;</code>
       */
      public java.lang.String getPayHtml() {
        java.lang.Object ref = payHtml_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payHtml_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *支付界面
       * </pre>
       *
       * <code>optional string payHtml = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPayHtmlBytes() {
        java.lang.Object ref = payHtml_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payHtml_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *支付界面
       * </pre>
       *
       * <code>optional string payHtml = 2;</code>
       */
      public Builder setPayHtml(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payHtml_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *支付界面
       * </pre>
       *
       * <code>optional string payHtml = 2;</code>
       */
      public Builder clearPayHtml() {
        
        payHtml_ = getDefaultInstance().getPayHtml();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *支付界面
       * </pre>
       *
       * <code>optional string payHtml = 2;</code>
       */
      public Builder setPayHtmlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payHtml_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.http.GetPayHTMLS)
    }

    // @@protoc_insertion_point(class_scope:protobuf.http.GetPayHTMLS)
    private static final protobuf.http.PayProto.GetPayHTMLS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.http.PayProto.GetPayHTMLS();
    }

    public static protobuf.http.PayProto.GetPayHTMLS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetPayHTMLS>
        PARSER = new com.google.protobuf.AbstractParser<GetPayHTMLS>() {
      public GetPayHTMLS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetPayHTMLS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetPayHTMLS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPayHTMLS> getParserForType() {
      return PARSER;
    }

    public protobuf.http.PayProto.GetPayHTMLS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_GetPayHTMLC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_GetPayHTMLC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_http_GetPayHTMLS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_http_GetPayHTMLS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016PayProto.proto\022\rprotobuf.http\"5\n\013GetPa" +
      "yHTMLC\022\017\n\007hOpCode\030\001 \001(\005\022\025\n\rorderRecordId" +
      "\030\002 \001(\t\"/\n\013GetPayHTMLS\022\017\n\007hOpCode\030\001 \001(\005\022\017" +
      "\n\007payHtml\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_http_GetPayHTMLC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_http_GetPayHTMLC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_GetPayHTMLC_descriptor,
        new java.lang.String[] { "HOpCode", "OrderRecordId", });
    internal_static_protobuf_http_GetPayHTMLS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_http_GetPayHTMLS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_http_GetPayHTMLS_descriptor,
        new java.lang.String[] { "HOpCode", "PayHtml", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
